<?php

return [
    'name' => 'hicms',
    'identifier' => 'hicms.hi.module',// 模块唯一标识[必填]，格式：模块名.[应用市场ID].module.[应用市场分支ID]
    'theme' => 'default',
    'mobile_theme' => 'default',
    'title' => '内容管理',
    'intro' => 'hi官方出品的内容管理模块',
    'author' => 'hiphp',
    'icon' => '',
    'version' => '1.0.1',
    'author_url' => '',
    'module_depend'=>[],
    'tables'=>['hicms_category','hicms_article'],
    'language'=>['china', 'english'], //安装时第1个语言包名为默认语言
    'db_prefix'=>'pre_',
    'config_icon'=>true,
    'config'=>[
        [
            'title'=>'配置1',
            'url'=>url('module/setting',['group'=>'hicms','tab'=>0]),
            'fields'=>[
                [
                    'name'=>'cms_input',//插件配置字段名
                    'group'=>'hicms',
                    'type'=>'input',
                    'title'=>'input测试',
                    'tips'=>'input测试',
                    'value'=>'',
                    'options'=>''
                ],
                [
                    'name'=>'cms_switch',
                    'group'=>'hicms',
                    'type'=>'switch',
                    'title'=>'switc测试',
                    'tips'=>'switc测试',
                    'value'=>'',
                    'options'=>'0:关闭;1:开启'
                ],
                [
                    'name'=>'cms_checkbox',
                    'group'=>'hicms',
                    'type'=>'checkbox',
                    'title'=>'checkbox测试',
                    'tips'=>'填在右上方',
                    'value'=>'1,2',
                    'options'=>'1:北京;2:上海;3:重庆',
                ],
                [
                    'name'=>'cms_image',
                    'group'=>'hicms',
                    'type'=>'image',
                    'title'=>'image测试',
                    'tips'=>'image测试',
                    'value'=>'',
                    'options'=>''
                ],
                [
                    'name'=>'cms_file',
                    'group'=>'hicms',
                    'type'=>'file',
                    'title'=>'file测试',
                    'tips'=>'file测试',
                    'value'=>'',
                    'options'=>''
                ],
                [
                    'name'=>'cms_radio',
                    'group'=>'hicms',
                    'type'=>'radio',
                    'title'=>'radio测试',
                    'tips'=>'radio测试',
                    'value'=>'',
                    'options'=>'0:关闭;1:开启'
                ],
                [
                    'name'=>'cms_datetime',
                    'group'=>'hicms',
                    'type'=>'datetime',
                    'title'=>'datetime测试',
                    'tips'=>'datetime测试',
                    'value'=>'',
                    'options'=>''
                ],
                [
                    'name'=>'cms_date',
                    'group'=>'hicms',
                    'type'=>'date',
                    'title'=>'date测试',
                    'tips'=>'date测试',
                    'value'=>'',
                    'options'=>''
                ],
                [
                    'name'=>'cms_date2',
                    'group'=>'hicms',
                    'type'=>'date',
                    'title'=>'date22测试',
                    'tips'=>'date22测试',
                    'value'=>'',
                    'options'=>''
                ],
                [
                    'name'=>'cms_title',
                    'group'=>'hicms',
                    'type'=>'textarea',
                    'title'=>'textarea测试',
                    'tips'=>'填在右上方',
                    'value'=>'这里是开发者助手描述哦',
                    'options'=>''
                ],
                [
                    'name'=>'cms_select',
                    'group'=>'hicms',
                    'type'=>'select',
                    'title'=>'select下拉保存',
                    'tips'=>'填在右上方',
                    'value'=>'',
                    'options'=>'ueditor:UEditor;umeditor:UMEditor;kindeditor:KindEditor',
                ]
            ]
        ],
        [
            'title'=>'配置2',
            'url'=>url('system/module/setting',['group'=>'hicms','tab'=>1]),
            'fields'=>[
                [
                    'name'=>'cms_des',
                    'group'=>'hicms',
                    'type'=>'textarea',
                    'title'=>'textarea测试',
                    'tips'=>'textarea测试',
                    'value'=>'textarea测试',
                    'options'=>''
                ],
                [
                    'name'=>'cms_color',
                    'group'=>'hicms',
                    'type'=>'color',
                    'title'=>'color类型测试',
                    'tips'=>'填在右上方22',
                    'value'=>'',
                    'options'=>''
                ],
                [
                    'name'=>'cms_color2',
                    'group'=>'hicms',
                    'type'=>'color',
                    'title'=>'color类型测试22',
                    'tips'=>'填在右上方22',
                    'value'=>'',
                    'options'=>''
                ],
                [
                    'name'=>'cms_array',
                    'group'=>'hicms',
                    'type'=>'array',
                    'title'=>'array测试',
                    'tips'=>'请按如下格式填写：<br>键值:键名<br>键值:键名',
                    'value'=>'',
                    'options'=>''
                ],
            ]
        ]
    ]
];