<?php
return [
    [
        'module'=>'plugin.devhelp',
        'title'=>'开发助手',
        'icon'=>'',
        'param'=>'',
        'url'=>'',
        'sort'=>0,
        'create_time'=>time(),
        'childs'=>[
            [
                'module'=>'plugin.devhelp',
                'title'=>'模块开发',
                'icon'=>'',
                'param'=>'_p=devhelp&_c=module&_a=index',
                'url'=>'system/plugin/run',
                'sort'=>0,
                'create_time'=>time(),
            ],
            [
                'module'=>'plugin.devhelp',
                'title'=>'插件开发',
                'icon'=>'',
                'param'=>'_p=devhelp&_c=plugin&_a=index',
                'url'=>'system/plugin/run',
                'sort'=>0,
                'create_time'=>time(),
        ]
        ]
    ]
];